services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: clientebase
      POSTGRES_USER: clientebase
      POSTGRES_PASSWORD: clientebase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clientebase -d clientebase"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_keycloak:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    ports:
      - "8080:8080"
    volumes:
      - /home/pauleatonc/Documents/AndesDigital/ClienteBaseKeycloak/kc-template:/opt/keycloak/themes/custom-theme
    command: start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
    networks:
      - app-network
    depends_on:
      postgres_keycloak:
        condition: service_healthy

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=clientebase.settings.local
    env_file:
      - ./backend/.env
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_ENV=LOCAL
      - VITE_KEYCLOAK_URL_LOCAL=http://localhost:8080
      - VITE_KEYCLOAK_REALM_LOCAL=test
      - VITE_KEYCLOAK_CLIENT_ID_LOCAL=frontintegration
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  postgres_data:
  postgres_keycloak_data:

networks:
  app-network:
    driver: bridge 